environments:
  dev:
    pipelines:
      - examplePipelineBuild
      - examplePipelineTesting
pipelines:
  terraformPlan:
    group: terraformBuild
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ciaranmcveigh5/projectOne
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              # artifacts:
              #  - build:
              #      source: build.txt
              #      destination: buildTest.txt
              tasks:
               - exec: # indicates type of task
                   command: echo building > build.txt
  terraformApply:
    group: terraformBuild
    materials:
      upstream:
        pipeline: terraformPlan
        stage: build
    stages: # list of stages in order
      approval: manual
      - testing: # name of stage
          clean_workspace: true
          jobs:
            unit: # name of the job
              tasks: 
               - exec: # indicates type of task
                   command: echo unit
            integration: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: echo integration
                   

